"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Compass, MessageSquare, Target, TrendingUp } from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";

import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { EmptyState, ErrorState, SkeletonList } from "@/components/ui/states";
import { api, ApiError } from "@/lib/api";
import { formatCurrency } from "@/lib/utils";
import type {
  CareerRoleRecommendation, SkillRecommendation, StudentProfile,
} from "@/types/api";

interface CareerGuidance {
  guidance: string;
  generated_by: string;
  top_skills: string[];
  target_role?: string | null;
  readiness_score?: number | null;
}

export function CareerRecommendations() {
  const queryClient = useQueryClient();

  const careers = useQuery({
    queryKey: ["recommendations", "careers"],
    queryFn: () => api.get<CareerRoleRecommendation[]>("/recommendations/careers", { limit: 8 }),
  });

  const skills = useQuery({
    queryKey: ["recommendations", "skills"],
    queryFn: () => api.get<SkillRecommendation[]>("/recommendations/skills", { limit: 8 }),
  });

  const guidance = useQuery({
    queryKey: ["recommendations", "guidance"],
    queryFn: () => api.get<CareerGuidance>("/recommendations/career-guidance"),
  });

  const setTarget = useMutation({
    mutationFn: (jobRoleId: string) =>
      api.patch<StudentProfile>("/students/me", { target_job_role_id: jobRoleId }),
    onSuccess: (profile) => {
      toast.success(`Target set: ${profile.target_job_role_title}`);
      void queryClient.invalidateQueries({ queryKey: ["student"] });
      void queryClient.invalidateQueries({ queryKey: ["recommendations"] });
    },
    onError: (error) =>
      toast.error(error instanceof ApiError ? error.message : "Could not set target"),
  });

  return (
    <>
      <PageHeader
        title="Career recommendations"
        description="Roles you are closest to, blended with how much the market is hiring for them."
      />

      {guidance.data && (
        <Card className="mb-6 border-brand-200 bg-brand-50/50 p-5">
          <div className="flex gap-3">
            <span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-surface text-brand-700">
              <MessageSquare className="size-4" aria-hidden />
            </span>
            <div className="min-w-0">
              <p className="text-sm font-semibold text-brand-900">Guidance for this month</p>
              <p className="mt-1 text-sm leading-relaxed text-brand-900/90">
                {guidance.data.guidance}
              </p>
              <p className="mt-2 text-2xs text-brand-900/60">
                Generated by the {guidance.data.generated_by} engine from your
                measured profile.
              </p>
            </div>
          </div>
        </Card>
      )}

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <h2 className="mb-3 text-lg">Roles you fit best</h2>
          {careers.isLoading && <SkeletonList count={4} rows={2} />}
          {careers.error && (
            <ErrorState error={careers.error} onRetry={() => void careers.refetch()} />
          )}
          {careers.data?.length === 0 && (
            <EmptyState
              icon={<Compass />}
              title="Not enough signal yet"
              description="Add skills or take an assessment — career fit is computed from your evidenced profile."
              action={
                <Link href="/student/assessment">
                  <Button size="sm">Take an assessment</Button>
                </Link>
              }
            />
          )}

          <div className="space-y-3">
            {careers.data?.map((role) => (
              <Card key={role.target_id} className="p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="text-[15px] font-semibold text-ink-900">
                      {role.target_title}
                    </p>
                    <p className="text-xs text-ink-500">
                      {role.family}
                      {role.salary_range[0]
                        ? ` · ${formatCurrency(role.salary_range[0])} – ${formatCurrency(role.salary_range[1])}`
                        : ""}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xl font-semibold tabular-nums text-brand-700">
                      {Math.round(role.readiness_score)}%
                    </p>
                    <p className="text-2xs text-ink-500">ready</p>
                  </div>
                </div>

                <div className="mt-3">
                  <Progress value={role.readiness_score} size="sm" />
                </div>

                <p className="mt-2.5 text-sm leading-relaxed text-ink-600">
                  {role.reason_summary}
                </p>

                {role.missing_skills.length > 0 && (
                  <div className="mt-2.5 flex flex-wrap gap-1">
                    <span className="text-2xs text-ink-500">To close:</span>
                    {role.missing_skills.slice(0, 5).map((skill) => (
                      <Badge key={skill} tone="warning">{skill}</Badge>
                    ))}
                  </div>
                )}

                <div className="mt-4 flex flex-wrap gap-2 border-t border-ink-100 pt-3.5">
                  <Button
                    size="sm"
                    isLoading={setTarget.isPending && setTarget.variables === role.target_id}
                    onClick={() => setTarget.mutate(role.target_id)}
                    leftIcon={<Target />}
                  >
                    Set as my target
                  </Button>
                  <Link href={`/student/skill-gap?role=${role.target_id}`}>
                    <Button size="sm" variant="secondary" rightIcon={<ArrowRight />}>
                      See the gap
                    </Button>
                  </Link>
                  <Badge tone="outline" size="md" className="ml-auto self-center">
                    Market demand {Math.round(role.demand_index)}/100
                  </Badge>
                </div>
              </Card>
            ))}
          </div>
        </div>

        <div>
          <h2 className="mb-3 text-lg">Skills to build next</h2>
          {skills.isLoading && <SkeletonList count={3} rows={2} />}
          <Card>
            <CardContent className="pt-5">
              {skills.data?.length === 0 ? (
                <EmptyState
                  className="border-0 bg-transparent py-4"
                  icon={<TrendingUp />}
                  title="No suggestions yet"
                />
              ) : (
                <ul className="divide-y divide-ink-100">
                  {skills.data?.map((skill) => (
                    <li key={skill.skill_id} className="py-3">
                      <div className="flex items-baseline justify-between gap-2">
                        <p className="truncate text-sm font-medium text-ink-900">
                          {skill.skill_name}
                        </p>
                        {skill.gap_priority && (
                          <Badge tone="danger">Priority {skill.gap_priority}</Badge>
                        )}
                      </div>
                      <p className="text-2xs text-ink-500">{skill.category}</p>
                      <ul className="mt-1 space-y-0.5">
                        {skill.reasons.slice(0, 2).map((reason) => (
                          <li key={reason} className="text-2xs text-ink-600">
                            • {reason}
                          </li>
                        ))}
                      </ul>
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
