"use client";

import { useQuery } from "@tanstack/react-query";
import { MessageSquare, RefreshCw } from "lucide-react";

import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState, ErrorState, SkeletonList } from "@/components/ui/states";
import { api } from "@/lib/api";

interface InterviewPrep {
  role_title: string;
  questions: { question: string; category: string; skill: string }[];
  focus_skills: string[];
  generated_by: string;
}

export function InterviewPrep() {
  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ["interview-prep"],
    queryFn: () => api.get<InterviewPrep>("/recommendations/interview-prep", { count: 10 }),
  });

  return (
    <>
      <PageHeader
        title="Interview preparation"
        description="Practice questions built around your strongest skills and your target role."
        actions={
          <Button
            variant="secondary"
            leftIcon={<RefreshCw />}
            isLoading={isFetching}
            onClick={() => void refetch()}
          >
            New set
          </Button>
        }
      />

      {isLoading && <SkeletonList count={5} rows={1} />}
      {error && <ErrorState error={error} onRetry={() => void refetch()} />}

      {data && (
        <>
          <Card className="mb-5 p-5">
            <p className="text-sm text-ink-600">
              Targeting <strong className="font-medium text-ink-900">{data.role_title}</strong>
              {data.focus_skills.length > 0 && ", focused on your strongest skills:"}
            </p>
            <div className="mt-2 flex flex-wrap gap-1">
              {data.focus_skills.map((skill) => (
                <Badge key={skill} tone="brand">{skill}</Badge>
              ))}
            </div>
          </Card>

          {data.questions.length === 0 ? (
            <EmptyState
              icon={<MessageSquare />}
              title="No questions generated"
              description="Add skills to your profile so questions can be tailored to what you know."
            />
          ) : (
            <ol className="space-y-3">
              {data.questions.map((question, index) => (
                <li key={`${question.question}-${index}`}>
                  <Card className="p-5">
                    <div className="flex gap-3">
                      <span className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-ink-100 text-xs font-semibold text-ink-600">
                        {index + 1}
                      </span>
                      <div className="min-w-0">
                        <p className="text-sm leading-relaxed text-ink-900">
                          {question.question}
                        </p>
                        <div className="mt-2 flex flex-wrap gap-1">
                          <Badge tone="outline">{question.category}</Badge>
                          {question.skill && <Badge tone="neutral">{question.skill}</Badge>}
                        </div>
                      </div>
                    </div>
                  </Card>
                </li>
              ))}
            </ol>
          )}

          <p className="mt-5 text-center text-xs text-ink-400">
            Generated by the {data.generated_by} engine. Practise answering out
            loud — the gap between knowing and explaining is where interviews
            are lost.
          </p>
        </>
      )}
    </>
  );
}
