"""Assessment catalogue: real questions, not placeholders.

Each entry is ``(skill_slug, difficulty, prompt, [(option, is_correct)], explanation)``
for choice questions, or a Likert block for self-assessment. Options are shuffled
at seed time is NOT done deliberately: display order is authored so the answer
position varies naturally across the bank.
"""
from __future__ import annotations

E, M, H = "EASY", "MEDIUM", "HARD"

# ---------------------------------------------------------------- Python ---
PYTHON = [
    ("python", E,
     "What does the expression `[x * 2 for x in range(3)]` evaluate to?",
     [("[0, 2, 4]", True), ("[2, 4, 6]", False), ("[0, 1, 2]", False), ("[1, 2, 3]", False)],
     "range(3) yields 0, 1, 2 and each is doubled, giving [0, 2, 4]."),
    ("python", E,
     "Which of these is a mutable built-in type in Python?",
     [("list", True), ("tuple", False), ("str", False), ("frozenset", False)],
     "Lists can be modified in place; tuples, strings and frozensets cannot."),
    ("python", M,
     "What is printed?\n\n```\ndef f(items=[]):\n    items.append(1)\n    return items\n\nprint(f()); print(f())\n```",
     [("[1]\n[1, 1]", True), ("[1]\n[1]", False), ("[1, 1]\n[1, 1]", False),
      ("It raises a TypeError", False)],
     "The default argument is evaluated once at definition time, so the same list "
     "is reused and accumulates values across calls. Use None as the default instead."),
    ("python", M,
     "Which statement about Python generators is correct?",
     [("They produce values lazily and hold only one item in memory at a time", True),
      ("They build the full sequence in memory before yielding", False),
      ("They can only be iterated using a while loop", False),
      ("They cannot be used inside a for loop", False)],
     "Generators yield on demand, which is why they are memory-efficient for large "
     "or infinite sequences."),
    ("python", M,
     "What does the `with` statement primarily guarantee?",
     [("The resource's cleanup runs even if an exception is raised", True),
      ("The block runs in a separate thread", False),
      ("The block is retried on failure", False),
      ("Variables inside the block are local to it", False)],
     "`with` invokes the context manager's __exit__, which runs on both the success "
     "and the exception path."),
    ("python", H,
     "Select every statement that is true about the GIL in CPython.",
     [("It prevents two threads from executing Python bytecode simultaneously", True),
      ("Multiprocessing side-steps it by using separate interpreters", True),
      ("It makes all Python programs single-threaded", False),
      ("I/O-bound threads can still overlap because the GIL is released during I/O", True)],
     "The GIL serialises bytecode execution, but it is released around blocking I/O, "
     "and separate processes each have their own GIL."),
    ("python", H,
     "What is the time complexity of checking `x in s` when `s` is a set of n items?",
     [("O(1) on average", True), ("O(n)", False), ("O(log n)", False), ("O(n log n)", False)],
     "Sets are hash tables, so average membership testing is constant time. The same "
     "check on a list is O(n)."),
]

# ------------------------------------------------------------------ SQL ----
SQL = [
    ("sql", E,
     "Which clause filters rows *before* any aggregation is applied?",
     [("WHERE", True), ("HAVING", False), ("ORDER BY", False), ("LIMIT", False)],
     "WHERE filters individual rows; HAVING filters the groups produced by GROUP BY."),
    ("sql", E,
     "Which join returns every row from the left table, with NULLs where the right has no match?",
     [("LEFT JOIN", True), ("INNER JOIN", False), ("CROSS JOIN", False), ("RIGHT JOIN", False)],
     "A LEFT JOIN preserves all left-hand rows regardless of whether a match exists."),
    ("sql", M,
     "What is wrong with `SELECT department, name, COUNT(*) FROM staff GROUP BY department;` in PostgreSQL?",
     [("`name` is neither aggregated nor in GROUP BY, so the query is rejected", True),
      ("COUNT(*) cannot be combined with GROUP BY", False),
      ("GROUP BY must come before SELECT", False),
      ("Nothing - it returns one row per member of staff", False)],
     "Every selected column must either appear in GROUP BY or be wrapped in an "
     "aggregate. PostgreSQL enforces this strictly."),
    ("sql", M,
     "Which index would best serve `WHERE tenant_id = ? AND created_at > ?`?",
     [("A composite index on (tenant_id, created_at)", True),
      ("A single index on created_at", False),
      ("Two separate single-column indexes only", False),
      ("No index - the planner handles it", False)],
     "A composite index ordered by equality column first, then the range column, "
     "lets the planner seek directly to the matching range."),
    ("sql", M,
     "What does a transaction's ACID 'Isolation' property guarantee?",
     [("Concurrent transactions do not observe each other's intermediate state", True),
      ("Data is written to disk immediately", False),
      ("Every transaction runs on its own connection", False),
      ("Failed transactions are retried automatically", False)],
     "Isolation controls what concurrent transactions can see of each other's "
     "uncommitted work."),
    ("sql", H,
     "Select every technique that genuinely helps a slow query on a large table.",
     [("Adding an index that covers the filter columns", True),
      ("Reading EXPLAIN ANALYZE to find the actual bottleneck", True),
      ("Replacing a correlated subquery with a join", True),
      ("Adding an index to every column in the table", False)],
     "Indexing everything slows writes and confuses the planner. Measure first, "
     "then index the access path you actually use."),
]

# ------------------------------------------------------- REST / backend ----
BACKEND = [
    ("rest-api", E,
     "Which HTTP status code should a successful resource creation return?",
     [("201 Created", True), ("200 OK", False), ("204 No Content", False), ("302 Found", False)],
     "201 signals a new resource exists, usually with its location in the response."),
    ("rest-api", E,
     "Which HTTP method is idempotent and used to replace a resource entirely?",
     [("PUT", True), ("POST", False), ("PATCH", False), ("CONNECT", False)],
     "PUT replaces the resource; repeating it leaves the same end state. PATCH "
     "applies a partial change."),
    ("rest-api", M,
     "A client sends a malformed JSON body. Which status is most appropriate?",
     [("400 Bad Request", True), ("500 Internal Server Error", False),
      ("404 Not Found", False), ("403 Forbidden", False)],
     "The fault is in the request, so it belongs in the 4xx range. 5xx means the "
     "server failed to handle a valid request."),
    ("rest-api", M,
     "What distinguishes 401 from 403?",
     [("401 means not authenticated; 403 means authenticated but not permitted", True),
      ("They are interchangeable", False),
      ("401 is for expired tokens only", False),
      ("403 means the resource does not exist", False)],
     "401 invites the client to authenticate; 403 says authentication succeeded but "
     "authorisation failed."),
    ("rest-api", M,
     "Why paginate list endpoints?",
     [("To bound response size, memory and query cost as data grows", True),
      ("To make the API harder to scrape", False),
      ("Because JSON cannot encode large arrays", False),
      ("To avoid using indexes", False)],
     "Unbounded lists degrade as the table grows and are a common source of "
     "production outages."),
    ("fastapi", M,
     "In FastAPI, what does declaring a Pydantic model as the request body achieve?",
     [("Automatic validation, parsing and OpenAPI schema generation", True),
      ("It only affects documentation", False),
      ("It disables type coercion", False),
      ("It makes the endpoint synchronous", False)],
     "The model is the single source of truth for validation and the generated "
     "OpenAPI schema."),
    ("fastapi", H,
     "Which are genuine reasons to use FastAPI's dependency injection?",
     [("Reusing authentication and database-session logic across endpoints", True),
      ("Overriding dependencies in tests without patching internals", True),
      ("Declaring shared query parameters once", True),
      ("Making endpoints run faster at runtime", False)],
     "Dependencies are about composition and testability, not raw speed."),
    ("system-design", H,
     "A read-heavy endpoint is slow under load. Which first step is most defensible?",
     [("Measure where time is actually spent before changing anything", True),
      ("Immediately add a caching layer", False),
      ("Rewrite the service in another language", False),
      ("Add more application servers", False)],
     "Optimising without measurement usually moves the bottleneck rather than "
     "removing it."),
]

# ----------------------------------------------------- frontend / React ----
FRONTEND = [
    ("javascript", E,
     "What does `const` guarantee in JavaScript?",
     [("The binding cannot be reassigned", True),
      ("The value is deeply immutable", False),
      ("The variable is global", False),
      ("The value is evaluated lazily", False)],
     "A const object's properties can still be mutated; only rebinding the name "
     "is prevented."),
    ("javascript", M,
     "What does `Promise.all` do when one promise rejects?",
     [("It rejects immediately with that error", True),
      ("It waits for all promises and returns partial results", False),
      ("It retries the failed promise", False),
      ("It resolves with undefined", False)],
     "Use Promise.allSettled when you need every outcome regardless of failures."),
    ("react", E,
     "What is the purpose of the `key` prop when rendering a list?",
     [("It lets React match elements across renders to preserve state", True),
      ("It sets the element's HTML id", False),
      ("It sorts the list", False),
      ("It is only needed in class components", False)],
     "Without stable keys React may reuse the wrong DOM node, causing lost input "
     "state and subtle bugs."),
    ("react", M,
     "When does a React component re-render?",
     [("When its state changes, its props change, or its parent re-renders", True),
      ("Only on a full page reload", False),
      ("Every animation frame", False),
      ("Only when useEffect runs", False)],
     "Rendering is driven by state and props; effects run *after* a render."),
    ("react", M,
     "What problem does `useEffect`'s dependency array solve?",
     [("It controls when the effect re-runs, preventing redundant or infinite runs", True),
      ("It makes the effect synchronous", False),
      ("It memoises the component", False),
      ("It replaces useState", False)],
     "An omitted array runs the effect after every render, which is a common cause "
     "of request loops."),
    ("web-accessibility", M,
     "Which practices genuinely improve accessibility?",
     [("Giving every interactive control an accessible name", True),
      ("Maintaining a visible keyboard focus indicator", True),
      ("Meeting minimum colour-contrast ratios", True),
      ("Using `div` with a click handler instead of `button`", False)],
     "A div with onClick is not focusable or announced as a control; use the "
     "semantic element."),
]

# ------------------------------------------------------- DevOps / Docker ---
DEVOPS = [
    ("docker", E,
     "What is the difference between a Docker image and a container?",
     [("An image is the immutable template; a container is a running instance of it", True),
      ("They are the same thing", False),
      ("An image runs, a container is stored", False),
      ("A container is a compressed image", False)],
     "Many containers can run from one image, each with its own writable layer."),
    ("docker", M,
     "Why order Dockerfile instructions so dependency installation precedes copying source?",
     [("So the dependency layer stays cached when only source code changes", True),
      ("Because COPY must come last", False),
      ("To reduce the number of layers to one", False),
      ("It has no effect on build time", False)],
     "Docker caches layers; a change invalidates that layer and everything after it."),
    ("docker", M,
     "Why should a production container avoid running as root?",
     [("It limits the blast radius if the process is compromised", True),
      ("Root containers cannot access the network", False),
      ("It makes the image smaller", False),
      ("Docker forbids it", False)],
     "Container isolation is not a security boundary you should rely on alone; "
     "drop privileges inside it too."),
    ("ci-cd", M,
     "What is the core purpose of continuous integration?",
     [("Every change is built and tested automatically, catching breakage early", True),
      ("Deploying to production on every commit", False),
      ("Replacing code review", False),
      ("Storing build artefacts", False)],
     "CI is about fast feedback on integration; continuous *delivery* covers "
     "releasing."),
    ("git", E,
     "What does `git rebase` do that `git merge` does not?",
     [("It replays commits onto a new base, producing linear history", True),
      ("It deletes the branch", False),
      ("It pushes to the remote", False),
      ("It resolves conflicts automatically", False)],
     "Rebasing rewrites commit history, which is why it should be avoided on "
     "shared branches."),
    ("kubernetes", H,
     "What does a Kubernetes readiness probe control?",
     [("Whether the pod receives traffic from its service", True),
      ("Whether the pod is restarted", False),
      ("How many replicas run", False),
      ("The pod's CPU limit", False)],
     "The liveness probe restarts unhealthy containers; readiness only gates traffic."),
]

# ------------------------------------------------------- ML / data sci ----
ML = [
    ("machine-learning", E,
     "What problem does a train/test split address?",
     [("Estimating how the model performs on data it has not seen", True),
      ("Making training faster", False),
      ("Reducing the dataset size", False),
      ("Balancing the classes", False)],
     "Evaluating on training data measures memorisation, not generalisation."),
    ("machine-learning", M,
     "A model scores 99% on training data and 62% on held-out data. What is happening?",
     [("Overfitting", True), ("Underfitting", False), ("Data leakage into the test set", False),
      ("The learning rate is too low", False)],
     "The model has learned noise specific to the training set. Regularisation, "
     "more data or a simpler model all help."),
    ("machine-learning", M,
     "For a dataset where 2% of cases are fraud, why is accuracy a poor metric?",
     [("Predicting 'not fraud' always scores 98% while catching nothing", True),
      ("Accuracy cannot be computed on imbalanced data", False),
      ("Accuracy only works for regression", False),
      ("It requires probability outputs", False)],
     "Use precision, recall, F1 or AUC-PR when the positive class is rare."),
    ("statistics", M,
     "What does a p-value actually represent?",
     [("The probability of data at least this extreme if the null hypothesis holds", True),
      ("The probability the null hypothesis is true", False),
      ("The probability the result is important", False),
      ("The size of the effect", False)],
     "A p-value says nothing about effect size or practical significance."),
    ("scikit-learn", M,
     "Why fit a scaler on the training set and only transform the test set?",
     [("Fitting on the test set leaks information from it into training", True),
      ("It is faster", False),
      ("Scalers cannot be refitted", False),
      ("The test set needs no scaling", False)],
     "Any statistic derived from test data and used in training inflates results."),
    ("responsible-ai", M,
     "A hiring model is more accurate for one demographic group than another. What is the responsible response?",
     [("Measure the disparity, report it, and do not deploy until it is addressed", True),
      ("Ship it because overall accuracy is high", False),
      ("Remove the demographic column and ship", False),
      ("Let the model decide and review later", False)],
     "Dropping the attribute does not remove the bias - proxies remain. Disparity "
     "must be measured and mitigated explicitly."),
]

# ---------------------------------------------------------- cyber ----------
SECURITY = [
    ("owasp", E,
     "What is the primary defence against SQL injection?",
     [("Parameterised queries that separate code from data", True),
      ("Escaping quotes by hand", False),
      ("Hiding error messages", False),
      ("Using a web application firewall alone", False)],
     "Parameterisation removes the possibility of data being parsed as SQL. Other "
     "measures are defence in depth, not the fix."),
    ("owasp", M,
     "Which defence stops reflected XSS most reliably?",
     [("Context-aware output encoding plus a strict Content-Security-Policy", True),
      ("Client-side input validation", False),
      ("Obfuscating JavaScript", False),
      ("Using POST instead of GET", False)],
     "Encoding at the point of output is what prevents injected markup from "
     "becoming executable."),
    ("application-security", M,
     "Why store password *hashes* with a slow algorithm like Argon2 or bcrypt?",
     [("To make offline brute-force attacks economically infeasible if the DB leaks", True),
      ("To make login faster", False),
      ("To compress the password", False),
      ("So passwords can be recovered later", False)],
     "Fast hashes such as SHA-256 allow billions of guesses per second; deliberate "
     "slowness is the point."),
    ("application-security", M,
     "What does CSRF exploit?",
     [("The browser automatically attaching cookies to cross-site requests", True),
      ("Weak password hashing", False),
      ("Unvalidated SQL input", False),
      ("Missing HTTPS", False)],
     "This is why a token the attacker's site cannot read, or SameSite cookies, "
     "breaks the attack."),
    ("iam", M,
     "What is the principle of least privilege?",
     [("Every identity gets only the permissions its task requires, and no more", True),
      ("Administrators should have no access", False),
      ("All users share one role for simplicity", False),
      ("Permissions are granted permanently", False)],
     "It limits how far an attacker can move after compromising one account."),
    ("network-security", H,
     "Select every measure that meaningfully protects data in transit.",
     [("TLS with modern cipher suites", True),
      ("HTTP Strict Transport Security", True),
      ("Certificate validation on the client", True),
      ("Base64 encoding the payload", False)],
     "Base64 is an encoding, not encryption - it provides no confidentiality."),
]

# ----------------------------------------------------------- aptitude ------
APTITUDE = [
    ("problem-solving", E,
     "A team of 4 completes a task in 6 days. Assuming equal output, how long would 3 people take?",
     [("8 days", True), ("4.5 days", False), ("6 days", False), ("12 days", False)],
     "Total work is 24 person-days; divided by 3 people that is 8 days."),
    ("problem-solving", M,
     "A server handles 1,200 requests per minute. What is that per second, rounded?",
     [("20", True), ("12", False), ("72", False), ("2", False)],
     "1200 / 60 = 20 requests per second."),
    ("problem-solving", M,
     "If a process fails 1 time in 500 and runs 10,000 times a day, roughly how many failures per day?",
     [("20", True), ("2", False), ("50", False), ("200", False)],
     "10,000 / 500 = 20."),
    ("critical-thinking", M,
     "A dashboard shows sign-ups doubled the day a campaign launched. What is the most rigorous conclusion?",
     [("The campaign may have contributed, but correlation alone does not establish cause", True),
      ("The campaign definitely caused the increase", False),
      ("The increase was random", False),
      ("Sign-ups will keep doubling", False)],
     "Other factors could coincide. A holdout or staggered rollout would give "
     "causal evidence."),
    ("critical-thinking", H,
     "Two metrics disagree about whether a change helped. What should you do first?",
     [("Check how each metric is defined and what population it covers", True),
      ("Pick the metric that supports shipping", False),
      ("Average the two", False),
      ("Discard both and ship on intuition", False)],
     "Disagreeing metrics usually mean different definitions, windows or segments."),
]

# --------------------------------------------------- soft skills (Likert) --
SOFT_SKILLS = [
    ("communication",
     "I can explain a technical decision to a non-technical stakeholder so they can act on it."),
    ("teamwork",
     "When a teammate is blocked, I notice and help without being asked."),
    ("leadership",
     "I have taken responsibility for a group's outcome, including when it went badly."),
    ("problem-solving",
     "When I hit an unfamiliar problem, I break it down and make progress without waiting for help."),
    ("time-management",
     "I consistently deliver what I committed to by the date I committed to."),
    ("adaptability",
     "When requirements change late, I adjust my approach without losing momentum."),
    ("ownership",
     "I follow a problem through to resolution even when it is outside my assigned scope."),
    ("presentation",
     "I can present work to a room and handle questions confidently."),
]

LIKERT_OPTIONS = [
    ("Not yet - I have had little opportunity to practise this", 0),
    ("Occasionally, with guidance", 1),
    ("Usually, in familiar situations", 2),
    ("Consistently, including in unfamiliar situations", 3),
    ("Consistently, and I coach others to do it", 4),
]

# assessment slug -> spec
ASSESSMENTS: list[dict] = [
    {
        "slug": "python-fundamentals",
        "title": "Python Fundamentals",
        "description": "Core Python: data structures, functions, generators and the "
                       "execution model. Establishes your measured Python level.",
        "type": "TECHNICAL", "domain": "Programming", "role": "python-developer",
        "primary_skill": "python", "duration": 20, "passing": 60,
        "questions": PYTHON,
    },
    {
        "slug": "sql-and-databases",
        "title": "SQL & Relational Databases",
        "description": "Querying, joins, aggregation, indexing and transactions.",
        "type": "TECHNICAL", "domain": "Databases", "role": "data-analyst",
        "primary_skill": "sql", "duration": 20, "passing": 60,
        "questions": SQL,
    },
    {
        "slug": "backend-api-engineering",
        "title": "Backend & API Engineering",
        "description": "HTTP semantics, REST design, FastAPI and service design "
                       "judgement.",
        "type": "SCENARIO", "domain": "Backend", "role": "backend-developer",
        "primary_skill": "rest-api", "duration": 25, "passing": 60,
        "questions": BACKEND,
    },
    {
        "slug": "frontend-react-engineering",
        "title": "Frontend & React Engineering",
        "description": "JavaScript semantics, React rendering and accessibility.",
        "type": "TECHNICAL", "domain": "Frontend", "role": "frontend-developer",
        "primary_skill": "react", "duration": 20, "passing": 60,
        "questions": FRONTEND,
    },
    {
        "slug": "devops-and-containers",
        "title": "DevOps, Containers & Delivery",
        "description": "Docker, CI/CD, Git and Kubernetes fundamentals.",
        "type": "TECHNICAL", "domain": "DevOps", "role": "devops-engineer",
        "primary_skill": "docker", "duration": 20, "passing": 60,
        "questions": DEVOPS,
    },
    {
        "slug": "machine-learning-foundations",
        "title": "Machine Learning Foundations",
        "description": "Generalisation, evaluation, leakage and responsible practice.",
        "type": "TECHNICAL", "domain": "Data & AI", "role": "ml-engineer",
        "primary_skill": "machine-learning", "duration": 25, "passing": 60,
        "questions": ML,
    },
    {
        "slug": "cybersecurity-essentials",
        "title": "Cybersecurity Essentials",
        "description": "OWASP risks, secure credential handling and access control.",
        "type": "TECHNICAL", "domain": "Security", "role": "cybersecurity-analyst",
        "primary_skill": "owasp", "duration": 20, "passing": 60,
        "questions": SECURITY,
    },
    {
        "slug": "analytical-aptitude",
        "title": "Analytical Aptitude",
        "description": "Quantitative reasoning and evidence-based judgement.",
        "type": "APTITUDE", "domain": "General", "role": None,
        "primary_skill": "problem-solving", "duration": 15, "passing": 50,
        "questions": APTITUDE,
    },
]
